@extends('layouts.front')

@section('content')

    <div class="container my-3">
        <div>
            <h4 class="text-center">TERMS AND CONDITIONS OF USE</h4>
            <p>
                This service includes subscriptions that automatically renew. Please read these terms and conditions of use carefully (in particular, section 6 “subscription fees and payment”) before starting a trial or completing a purchase for our website’s auto-renewing subscription service. To avoid being charged you must affirmatively cancel your subscription at least 24 hours before the end of the current subscription period.
            </p>
            <p>
                If you are unsure how to cancel a subscription or a free trial, please visit our website. We also aim to provide information about our subscription policies at or near the point of purchase. Please review these policies prior to making purchases. You may wish to make a printscreen of this information for your reference.
            </p>

            <h6>1. ACCEPTANCE OF TERMS</h6>

            <p>1.1. The provisions of these terms and conditions of use (the "Terms") govern the relationship between you and Degudegu Limited (reg. No. 303020228) with registered office Mastupio 26, Rainiai, LT-88401 Lithuania ("we", "us", "our" or the "Company") regarding your use of the Company’s websites and related services (the “website” or "service"), including all information, text, graphics, software, and services, available for your use (the “Content”).</p>
            <p>1.2. These Terms establish a legally binding contractual relationship between you and the Company. For this reason, PLEASE READ THE TERMS CAREFULLY BEFORE USING THE SERVICE.</p>
            <p>1.3. Please review also our Privacy Policy. The terms of the Privacy Policy and other supplemental terms, policies or documents that may be posted on the Service from time to time are hereby expressly incorporated herein by reference. We reserve the right, in our sole discretion, to make changes or modifications to these Terms at any time and for any reason.</p>
            <p>1.4. Any translation from English version is provided for your convenience only. In the event of any difference in meaning or interpretation between the English language version of these Terms available at https://babyledweaning.me/terms, and any translation, the English language version will prevail. The original English text shall be the sole legally binding version</p>
            <p>1.5. Unless otherwise expressly provided herein, we will alert you about any changes by updating the "Last updated" date of these Terms and you waive any right to receive specific notice of each such change.</p>
            <p>1.6. THESE TERMS CONTAIN IMPORTANT DISCLAIMERS (SECTION 2), DISCLAIMER OF WARRANTIES (SECTION 8), LIMITATION OF LIABILITY (SECTION 9), AS WELL AS PROVISIONS THAT WAIVE YOUR RIGHT TO A JURY TRIAL, RIGHT TO A COURT HEARING AND RIGHT TO PARTICIPATE IN A CLASS ACTION (ARBITRATION AND CLASS ACTION WAIVER IN SECTION 12). UNLESS YOU OPT OUT WITHIN 30 DAYS OF FIRST USE OF OUR SERVICE AS PROVIDED FOR IN SECTION 12, ARBITRATION IS THE EXCLUSIVE REMEDY FOR ANY AND ALL DISPUTES AND IS MANDATORY EXCEPT AS SPECIFIED BELOW IN SECTION 12.</p>
            <p>1.7. IF YOU DO NOT AGREE WITH ANY PART OF THESE TERMS, OR IF YOU ARE NOT ELIGIBLE OR AUTHORIZED TO BE BOUND BY THESE TERMS, THEN DO NOT ACCESS OR USE THE SERVICE.</p>

            <h6>2. PROFILE REGISTRATION</h6>

            <p>2.1. In order to use certain features of the Service, you may need to register your profile ("Profile") and provide certain information about yourself as prompted by the registration form.</p>
            <p>2.2. If you register the Profile, you represent and warrant to the Company that: (i) all required registration information you submit is truthful and accurate; (ii) you will maintain the accuracy of such information; and (iii) your use of the Service does not violate any applicable law or regulation or these Terms. Otherwise, the Service may not operate correctly, and we may not be able to contact you with important notices.</p>
            <p>2.3. The Service is not intended to be used by individuals under age of 16. You hereby represent and warrant to the Company that you meet the foregoing qualification. All users who are minors in the jurisdiction in which they reside (generally under the age of 18) must have the permission of, and be directly supervised by, their parent or guardian to use the Service. If you are a minor, you must have your parent or guardian read and agree to these Terms prior to you using the Service.</p>
            <p>2.4. The Company reserves the right to suspend or terminate your Profile, or your access to the Service, with or without notice to you, in the event that you breach these Terms.</p>
            <p>2.5. You are responsible for maintaining the confidentiality of your Profile login information and are fully responsible for all activities that occur under your Profile. You agree to immediately notify the Company of any unauthorized use, or suspected unauthorized use of your Profile or any other breach of security. The Company cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.</p>

            <h6>3. SERVICE</h6>

            <p>3.1. You acknowledge that all the text, images, marks, logos, compilations (meaning the collection, arrangement and assembly of information), data, other content, software and materials displayed on the Service or used by the Company to operate the Service is proprietary to us or to third parties.</p>
            <p>3.2. The Company expressly reserves all rights, including all intellectual property rights, in all of the foregoing, and except as expressly permitted by these Terms, any use, redistribution, sale, decompilation, reverse engineering, disassembly, translation or other exploitation of them is strictly prohibited. The provision of the Service does not transfer to you or any third party any rights, title or interest in or to such intellectual property rights.</p>
            <p>3.3. The information you submit to us as part of your registration, and any data, text and other material that you may submit or post to the website  ("User Content") remain your intellectual property, and the Company does not claim any ownership of the copyright or other proprietary rights in such registration information and the User Content. Notwithstanding the foregoing, you agree that the Company may retain copies of all registration information and the User Content and use such information and the User Content as reasonably necessary for or incidental to its operation of the Service and as described in these Terms and the Privacy Policy.</p>
            <p>3.4. You grant the Company the non-exclusive, worldwide, transferable, perpetual, irrevocable right to publish, distribute, publicly display and perform the User Content in connection with the Service.</p>
            <p>3.5. Subject to these Terms, the Company grants you a non-transferable, non-exclusive, license (without the right to sublicense) to use the Service solely for your personal, non-commercial purposes.</p>
            <p>3.6. You agree, and represent and warrant, that your use of the Service, or any portion thereof, will be consistent with the foregoing license, covenants and restrictions and will neither infringe nor violate the rights of any other party or breach any contract or legal duty to any other parties. In addition, you agree that you will comply with all applicable laws, regulations and ordinances relating to the Service or your use of it, and you will be solely responsible for your own individual violations of any such laws.</p>
            <p>3.7. You are solely responsible for obtaining the equipment and telecommunication services necessary to access the Service, and all fees associated therewith (such as computing devices and Internet service provider and airtime charges).</p>
            <p>3.8. We retain the right to implement any changes to the Service (whether to free or paid features) at any time, with or without notice. You acknowledge that a variety of Company's actions may impair or prevent you from accessing the Service at certain times and/or in the same way, for limited periods or permanently, and agree that the Company has no responsibility or liability as a result of any such actions or results, including, without limitation, for the deletion of, or failure to make available to you, any content or services.</p>
            <p>3.9. The Company has no obligation to provide you with customer support of any kind. However, the Company may provide you with customer support from time to time, at the Company's sole discretion.</p>

            <h6>4. THIRD PARTY ADS, OTHER USERS</h6>

            <p>4.1. The Service may contain links to third party websites or resources and advertisements for third parties (collectively, "Third Party Ads"). Such Third Party Ads are not under the control of the Company and the Company is not responsible for any Third Party Ads. The Company provides these Third Party Ads only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third Party Ads. Advertisements and other information provided by Third Party Sites Ads may not be wholly accurate. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources. When you link to a third party site, the applicable service provider's terms and policies, including privacy and data gathering practices govern. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party. Your transactions and other dealings with Third Party Ads that are found on or through the website, including payment and delivery of related goods or services, are solely between you and such merchant or advertiser.</p>
            <p>4.2. Each user of the Service is solely responsible for any and all his or her User Content. Because we do not control the User Content, you acknowledge and agree that we are not responsible for any User Content and we make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content, and we assume no responsibility for any User Content. Your interactions with other Service users are solely between you and such user. You agree that the Company will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Service user, we are under no obligation to become involved.</p>

            <h6>5. SUBSCRIPTION FEES AND PAYMENT</h6>

            <p>5.1. Certain features of the Service may be offered on a subscription basis for a fee. You may purchase a subscription directly from the Company paying a subscription fee in advance on a recurring interval disclosed to you prior to your purchase; or (2) pre-payment giving you access to the Service for a specific time period (together or separately “Purchase”).</p>
            <p>5.2. To the maximum extent permitted by applicable laws, we may change Purchase fees at any time. We will give you reasonable notice of any such pricing changes by posting the new prices on the website and/or by sending you an e-mail notification, or in other prominent way. If you do not wish to pay the new fees, you can cancel the applicable subscription prior to the change going into effect or/and abstain from pre-paying for access to the Service.</p>
            <p>5.3. You authorize us to charge the applicable fees to the payment card that you submit.</p>
            <p>5.4. By signing up for certain subscriptions, you agree that your subscription may be automatically renewed. Unless you cancel your subscription you authorize us to charge you for the renewal term. The period of auto-renewal will be the same as your initial subscription period unless otherwise disclosed to you on the Service. The renewal rate will be no more than the rate for the immediately prior subscription period, excluding any promotional and discount pricing, unless we notify you of a rate change prior to your auto-renewal. You must cancel your subscription in accordance with the cancellation procedures disclosed to you for the particular subscription. We will not refund fees that may have accrued to your account and will not prorate fees for a cancelled subscription.</p>
            <p>5.5. We may offer a trial subscription for the Service. Trial provides you access to the Service for a period of time, with details specified when you sign up for the offer. Unless you cancel before the end of the free trial, or unless otherwise stated, your access to the Service will automatically continue and you will be billed the applicable fees for the Service. It is ultimately your responsibility to know when the free trial will end. We reserve the right, in our absolute discretion, to modify or terminate any free trial offer, your access to the Service during the free trial, or any of these terms without notice and with no liability. We reserve the right to limit your ability to take advantage of multiple free trials.</p>
            <p>5.6. The Service and your rights to use it expire at the end of the paid period of your subscription. If you do not pay the fees or charges due, we may make reasonable efforts to notify you and resolve the issue; however, we reserve the right to disable or terminate your access to the Service (and may do so without notice).</p>
            <p>5.7. You agree that the Purchase is final, that Company will not refund any transaction once it has been made and that the Purchase cannot be canceled. When you make the Purchase, you acknowledge and agree that all Purchases are non-refundable or exchangeable. Since the Service is of a digital nature, we cannot accept any request for refunds and therefore your right of withdrawal is lost at this point. The Company may provide refunds at its own discretion and subject to our policies that may be published from time to time.</p>
            <p>5.8. We may post clear and conspicuous subscription terms from time to time on our website.</p>

            <h6>6. USER REPRESENTATIONS AND RESTRICTIONS</h6>

            <p>6.1. By using the Service, you represent and warrant that:</p>
            <p>(a)    you have the legal capacity and you agree to comply with these Terms;</p>
            <p>(b)    you are not under the age of 16;</p>
            <p>(c)    you will not access the Service through automated or non-human means, whether through a bot, script or otherwise;</p>
            <p>(d)    you will not use the Service for any illegal or unauthorized purpose;</p>
            <p>(e)    you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a "terrorist supporting" country;</p>
            <p>(f)    you are not listed on any U.S. government list of prohibited or restricted parties; and</p>
            <p>(g)    your use of the Service will not violate any applicable law or regulation.</p>
            <p>6.2. If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to refuse any and all current or future use of the Service (or any portion thereof).</p>
            <p>6.3. You may not access or use the Service for any purpose other than that for which we make the Service available. The Service may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.</p>
            <p>6.4. As a user of the Service, you agree not to:</p>
            <p>(a)    systematically retrieve data or other content from the Service to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us;</p>
            <p>(b)    make any unauthorized use of the Service;</p>
            <p>(c)    make any modification, adaptation, improvement, enhancement, translation, or derivative work from the Service;</p>
            <p>(d)    use the Service for any revenue generating endeavor, commercial enterprise, or other purpose for which it is not designed or intended;</p>
            <p>(e)    make the Service available over a network or other environment permitting access or use by multiple devices or users at the same time;</p>
            <p>(f)    use the Service for creating a product, service, or software that is, directly or indirectly, competitive with or in any way a substitute for the Service;</p>
            <p>(g)    use any proprietary information or any of our interfaces or our other intellectual property in the design, development, manufacture, licensing, or distribution of any applications, accessories, or devices for use with the Service;</p>
            <p>(h)    circumvent, disable, or otherwise interfere with security-related features of the Service;</p>
            <p>(i)    engage in unauthorized framing of or linking to the Service;</p>
            <p>(j)    interfere with, disrupt, or create an undue burden on the Service or the networks or services connected to the Service;</p>
            <p>(k)    decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Service;</p>
            <p>(l)    attempt to bypass any measures of the Service designed to prevent or restrict access to the Service, or any portion of the Service;</p>
            <p>(m)    upload or distribute in any way files that contain viruses, worms, trojans, corrupted files, or any other similar software or programs that may damage the operation of another's computer;</p>
            <p>(n)    use, launch, develop, or distribute any automated system, including without limitation, any spider, robot, cheat utility, scraper, or offline reader that accesses the Service, or using or launching any unauthorized script or other software;</p>
            <p>(p)    disparage, tarnish, or otherwise harm, in our opinion, us and/or the Service;</p>
            <p>(q)    use the Service in a manner inconsistent with any applicable laws or regulations; or</p>
            <p>(r)    otherwise infringe these Terms.</p>

            <h6>7. ADDITIONAL DISCLAIMER OF WARRANTIES</h6>

            <p>a.Basic Disclaimers of Warranties</p>
            <p>Except where otherwise inapplicable or prohibited by law to the fullest extent permitted by law, you expressly understand and agree that your use of the Service is at your sole risk, and the Service is provided on an "as is" and "as available" basis.</p>
            <p>The Company or its affiliates, officers, employees, agents, partners, and licensors expressly disclaim all warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement as well as any and all warranties as to products or services offered by businesses listed on the service. The released parties make no, and expressly disclaim any warranty that:</p>
            <p>(i) the Service will meet your requirements,</p>
            <p>(ii) the Service will be uninterrupted, timely, secure, or error-free,</p>
            <p>(iii) the results that may be obtained from the use of the Service, including data, will be accurate or reliable,</p>
            <p>(iv) the quality of any data or service available on the Service will meet your expectations, and</p>
            <p>(v) any errors in the service will be corrected.</p>
            <p>Any material obtained through the use of the Service is accessed at your own discretion and risk, and you will be solely responsible for any damage to your computer system or mobile device or loss of data that results from the use of any such material.</p>
            <p>We cannot guarantee and do no promise any specific results from use of the website and/or the Service. You agree also to take the risks of interruption of the Service for any technical reasons.</p>
            <p>b. Absence of Any Advice on the Service</p>
            <p>Any statement that may be posted on the Service is for informational and entertainment purposes only and is not intended to replace or substitute for any professional financial, technical, legal, or other advice.</p>
            <p>The Company makes no representations or warranties and, to the fullest extent permitted by law, expressly disclaims any and all liability relating to your reliance on the statements or other information offered or provided within or through the Service.</p>
            <p>c. Change of Website Information and Service</p>
            <p>We may change all the information provided on the Service at our sole discretion without notice.</p>
            <p>We may at any time modify or discontinue, temporarily or permanently, the Service (or any part thereof) at our sole discretion with or without notice. You agree that we shall not be liable to you or any third party for any modification, suspension or discontinuance of the Service.</p>

            <h6>8. LIMITATION OF LIABILITY</h6>

            <p>8.1. IN NO EVENT SHALL WE (AND OUR AFFILIATES) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM THESE TERMS OR YOUR USE OF, OR INABILITY TO USE, THE SERVICE (INCLUDING THE CONTENT), OR THIRD PARTY ADS, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SERVICE (INCLUDING THE CONTENT AND USER CONTENT), AND THIRD PARTY ADS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTING SYSTEM OR LOSS OF DATA RESULTING THEREFROM.</p>
            <p>8.2. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, YOU AGREE THAT THE AGGREGATE LIABILITY OF THE COMPANY TO YOU FOR ANY AND ALL CLAIMS ARISING FROM THE USE OF THE WEBSITE, CONTENT OR SERVICE IS LIMITED TO THE AMOUNTS YOU HAVE PAID TO THE COMPANY FOR ACCESS TO AND USE OF THE SERVICE. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE TERMS BETWEEN THE COMPANY AND YOU.</p>
            <p>8.3. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU AND YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.</p>

            <h6>9. INDEMNITY</h6>

            <p>You agree to indemnify and hold the Company, its successors, subsidiaries, affiliates, any related companies, its suppliers, licensors and partners, and the officers, directors, employees, agents and representatives of each of them harmless, including costs and attorneys' fees, from any claim or demand made by any third party due to or arising out of (i) your use of the Service, (ii) your User Content, or (ii) your violation of these Terms.</p>
            <p>The Company reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of the Company. The Company will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>

            <h6>10. INTERNATIONAL USE</h6>

            <p>The Company makes no representation that the Service is accessible, appropriate or legally available for use in your jurisdiction, and accessing and using the Service is prohibited from territories where doing so would be illegal. You access the Service at your own initiative and are responsible for compliance with local laws.</p>

            <h6>11. MANDATORY BINDING ARBITRATION AND CLASS ACTION WAIVER</h6>

            <p>Please read this arbitration provision carefully to understand your rights.</p>
            <p>(a) All claims must be resolved through binding arbitration by a neutral arbitrator;</p>
            <p>(b) You are waiving the right to a trial by jury; the rights that you would have if you went to court, such as discovery or the right to appeal, may be more limited or may not exist;</p>
            <p>(c) You may only bring a claim in your individual capacity and not as a plaintiff (lead or otherwise) or class member in any purported class or representative proceeding;</p>
            <p>(d) The arbitrator may not consolidate proceedings or claims or otherwise preside over any form of a representative or class proceeding.</p>
            <p>a. Mandatory Arbitration</p>
            <p>This arbitration agreement provides that all disputes must be resolved through BINDING ARBITRATION whenever you or we choose to submit or refer a dispute to arbitration. You and the Company, and each of our respective agents, corporate parents, subsidiaries, affiliates, predecessors in interest, successors, and assigns, agree to BINDING ARBITRATION (except for matters that may be taken to small claims court), as the exclusive form of dispute resolution except as provided for below, for all disputes and claims arising out of or relating to these Terms (including the Privacy Policy) or the Service, unless you are located in a jurisdiction that prohibits the exclusive use of arbitration for dispute resolution. YOU AGREE THAT, BY ENTERING INTO THESE Terms, you and we are each waiving the right to a trial by jury or to participate in a class action.</p>
            <p>b. Waiver of Class Action and Collective Relief</p>
            <p>There shall be no right or authority for any claims to be arbitrated or litigated on a class action, joint or consolidated basis or on bases involving claims brought in a purported representative capacity on behalf of the general public, other users of the Services, or any other persons. The arbitrator may award relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that individual party’s claim. The arbitrator may not award relief for or against anyone who is not a party. The arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of a representative or class proceeding. This waiver of class actions and collective relief is an essential part of this arbitration provision and cannot be severed from it.</p>
            <p>c. Arbitration Procedures.</p>
            <p>Any disputes arising out of or in connection with these Terms, including any questions regarding its existence, validity, or termination, shall be referred to and finally resolved by BINDING ARBITRATION under the London Court of International Arbitration (“LCIA”) Rules in force when the Notice of Arbitration is submitted, which Rules are deemed to be incorporated by reference into this clause.</p>
            <p>- Overview. Arbitration is an alternative to litigation where a neutral person (the arbitrator) hears and decides the parties’ dispute. Arbitration proceedings are designed to provide parties with a fair hearing in a manner that is faster and less formal than court proceedings. The following procedures (the “Arbitration Procedures”) are applicable to all arbitration proceedings involving you and us.</p>
            <p>- Administrator. The administrator for the arbitration is the LCIA, a non-profit organization that is not affiliated with us. The arbitrator who will hear and decide your dispute will be appointed by the LCIA in accordance with its rules. Information about the LCIA’s rules and fees can be found at: https://www.lcia.org//Dispute_Resolution_Services/lcia-arbitration-rules-2014.aspx.</p>
            <p>- Choice of Law. The governing law applicable to the arbitration agreement and the arbitration shall be the laws of England and Wales (also known as English Law), without regard to English Law’s conflict of laws rules.</p>
            <p>- Language. The language of the arbitration shall be English.</p>
            <p>- Applicable Rules. The arbitration will be governed by the LCIA’s Arbitration Rules (“LCIA Rules”), as modified by these Arbitration Procedures. If there is any inconsistency between the LCIA’s Rules and these Arbitration Procedures, the Arbitration Procedures will control. However, if the arbitrator determines that strict application of the Arbitration Procedures would not result in a fundamentally fair arbitration, the arbitrator may make any order necessary to provide a fundamentally fair arbitration that is consistent with the LCIA Rules.</p>
            <p>- Commencing an Arbitration. To commence an arbitration against us, you must complete a written request for arbitration, submit it to the LCIA, and send a copy to us at email address indicate in Section 15. To learn more about commencing an arbitration and to obtain a form to institute arbitration, see the LCIA’s online filing page, https://onlinefiling.lcia.org/. You may represent yourself in the arbitration or have a lawyer (or some other representative) act on your behalf. Upon receipt of an arbitration claim, we may assert any counterclaims it may have against the complaining party.</p>
            <p>- Fees. You are responsible for paying your portion of the fees set forth in the LCIA’s Schedule of LCIA Arbitration Costs and as determined by the Arbitral Tribunal under LCIA Rules. We will pay all remaining fees. If your claim against us is for less than USD1,000, we will pay all fees. You may hire an attorney to represent you in arbitration. You are responsible for your attorneys’ fees and additional costs. Notwithstanding anything in this Arbitration Provision to the contrary, we will pay all fees and costs that we are required by law to pay.</p>
            <p>- Selection of the Arbitrator. The arbitrator who will hear and decide your dispute will be appointed by the LCIA in accordance with its rules.</p>
            <p>- Discovery. Each party may (a) request relevant, non-privileged documents from the other party; and (b) request that the other party provide the particulars of its claims or defenses. Any such discovery requests must be served on the other party within 10 days after the arbitrator’s appointment. The responding party shall provide the requesting party with all responsive, non-privileged documents, the requested particulars, and/or any objections to the requests within 15 days after receipt of the requests. Any disputes about discovery or requests for extensions shall be submitted promptly to the arbitrator for prompt resolution. In ruling on any discovery dispute or extension request, the arbitrator shall take into consideration the nature, amount, and scope of the underlying arbitration claim, the cost and other effort what would be involved in providing the requested discovery, the case schedule, and whether the requested discovery is necessary for the adequate preparation of a claim or defense.</p>
            <p>- Communications with the Arbitrator. Whenever communicating with the arbitrator, the parties must include each other – for example, by including the other party on a telephone conference call and copying the other party on any written submissions, such as letters or emails. To the extent practicable, conferences with the arbitrator will take place by telephone conference call or email. Ex parte communications are not permitted with any arbitrator.</p>
            <p>- Confidentiality. Upon either party’s request, the arbitrator will issue an order requiring that confidential information of either party disclosed during the arbitration (whether in documents or orally) may not be used or disclosed except in connection with the arbitration or a proceeding to enforce the arbitration award and that any permitted filing of confidential information must be done under seal.</p>
            <p>- Arbitration Award. The arbitrator will render a written decision within 14 days after the hearing or, if no hearing was held, within 30 days after any rebuttal or supplemental statements are due. The decision must clearly specify the relief, if any, awarded and contain a brief statement of the reasons for the award.</p>
            <p>- Waiver of Appeal. The parties waive any right to refer any question of law and any right of appeal on the law and/or the merits to any court.</p>
            <p>- Survivability. This arbitration provision shall survive termination of this Terms.</p>

            <h6>12. GOVERNING LAW</h6>

            <p>12.1. These Terms shall be governed in accordance with the laws of England and Wales (excluding its body of law governing conflicts of law).</p>
            <p>12.2. To the extent that any action relating to any dispute hereunder is for whatever reason not submitted to arbitration, each of the parties submits to the exclusive jurisdiction to the courts of England and Wales to settle any disputes which may arise out of or in connection with this Terms and that accordingly proceedings must be brought in such courts.</p>
            <p>12.3. The parties irrevocably submit to the personal jurisdiction and venue of the courts of England and waive any defenses of improper venue or forum non conveniens.</p>
            <p>13. MISCELLANEOUS PROVISIONS</p>
            <p>13.1. No delay or omission by us in exercising any of our rights occurring upon any noncompliance or default by you with respect to these Terms will impair any such right or be construed to be a waiver thereof, and a waiver by the Company of any of the covenants, conditions or agreements to be performed by you will not be construed to be a waiver of any succeeding breach thereof or of any other covenant, condition or agreement hereof contained.</p>
            <p>13.2. Subject to Section 12, if any provision of these Terms is found to be invalid or unenforceable, then these Terms will remain in full force and effect and will be reformed to be valid and enforceable while reflecting the intent of the parties to the greatest extent permitted by law.</p>
            <p>13.3. Except as otherwise expressly provided herein, these Terms set forth the entire agreement between you and the Company regarding its subject matter, and supersede all prior promises, agreements or representations, whether written or oral, regarding such subject matter.</p>
            <p>13.4. The Company may transfer or assign any and all of its rights and obligations under these Terms to any other person, by any way, including by novation, and by accepting these Terms you give the Company consent to any such assignment and transfer. You confirm that placing on the Service of a version of these Terms indicating another person as a party to the Terms shall constitute valid notice to you of the transfer of Company's rights and obligations under the Terms (unless otherwise is expressly indicated).</p>
            <p>13.5. All information communicated on the Service is considered an electronic communication. When you communicate with us through or on the Service or via other forms of electronic media, such as e-mail, you are communicating with us electronically. You agree that we may communicate electronically with you and that such communications, as well as notices, disclosures, agreements, and other communications that we provide to you electronically, are equivalent to communications in writing and shall have the same force and effect as if they were in writing and signed by the party sending the communication. You further acknowledge and agree that by clicking on a button labeled "SUBMIT", "CONTINUE", "REGISTER", "I AGREE" or similar links or buttons, you are submitting a legally binding electronic signature and are entering into a legally binding contract. You acknowledge that your electronic submissions constitute your agreement and intent to be bound by these Terms. YOU HEREBY AGREE TO THE USE OF ELECTRONIC SIGNATURES, CONTRACTS, ORDERS AND OTHER RECORDS AND TO ELECTRONIC DELIVERY OF NOTICES, POLICIES AND RECORDS OF TRANSACTIONS INITIATED OR COMPLETED THROUGH THE SERVICE.</p>
            <p>13.6. In no event shall the Company be liable for any failure to comply with these Terms to the extent that such failure arises from factors outside the Company's reasonable control.</p>
            <p>14. CONTACT</p>
            <p>If you want to send any notice under these Terms or have any questions regarding the Service, you may contact us at: support@babyledweaning.me</p>
            <p>I HAVE READ THESE TERMS AND AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE.</p>
            <p>Degudegu Limited (reg. No. 303020228 with registered office at Mastupio 26, Rainiai, LT-88401, Lithuania)</p>
            <p>Last Updated: 18 April 2021</p>

        </div>
    </div>

@endsection